// Game configuration constants
export const CONFIG = {
  // Internal game resolution
  GAME_WIDTH: 420,
  GAME_HEIGHT: 680,

  // Player
  PLAYER_WIDTH: 28,
  PLAYER_HEIGHT: 22,
  PLAYER_SPEED: 4.5,
  PLAYER_LIVES: 3,
  PLAYER_INVINCIBLE_TIME: 2000,
  PLAYER_Y_OFFSET: 60, // distance from bottom

  // Dash
  DASH_SPEED: 14,
  DASH_DURATION: 140,     // ms of active dash motion
  DASH_COOLDOWN: 1200,    // ms before dash is ready again
  DASH_IFRAME_TIME: 260,  // ms of invulnerability during dash

  // Shooting
  FIRE_RATE: 320,
  BULLET_SPEED: 7,
  BULLET_WIDTH: 3,
  BULLET_HEIGHT: 10,

  // Shard chains
  SHARD_SIZE: 20,
  SHARD_PADDING: 2,
  SHARD_BASE_SPEED: 1.0,
  SHARD_DROP_STEP: 22,
  SHARD_SPEED_INCREMENT: 0.1,
  SHARD_HP: 1,

  // Waves
  WAVE_BASE_CHAINS: 2,
  WAVE_CHAIN_INCREMENT: 0.8,
  WAVE_MAX_CHAINS: 8,
  WAVE_BASE_LENGTH: 6,
  WAVE_LENGTH_INCREMENT: 0.5,
  WAVE_MAX_LENGTH: 14,
  WAVE_INTRO_TIME: 2000,
  WAVE_CLEAR_TIME: 1500,

  // Obstacles
  OBSTACLE_MIN_PER_WAVE: 2,
  OBSTACLE_MAX_PER_WAVE: 12,
  OBSTACLE_SIZE: 24,
  OBSTACLE_MIN_Y: 100,
  OBSTACLE_MAX_Y: 520,

  // Hazards
  HAZARD_ORB_SPEED: 1.8,
  HAZARD_ORB_SIZE: 12,
  HAZARD_RICOCHET_SPEED: 3.0,
  HAZARD_RICOCHET_SIZE: 10,
  HAZARD_DIVER_SPEED: 4.5,
  HAZARD_DIVER_SIZE: 14,
  HAZARD_SPAWN_INTERVAL_BASE: 5000,
  HAZARD_SPAWN_INTERVAL_MIN: 1800,

  // Scoring
  SCORE_PER_SHARD: 10,
  SCORE_CHAIN_SPLIT_BONUS: 25,
  COMBO_TIMEOUT: 1200,
  COMBO_MULTIPLIER_STEP: 0.5,
  COMBO_MAX_MULTIPLIER: 5,
  WAVE_CLEAR_BONUS: 200,
  FLAWLESS_WAVE_BONUS: 300,
  COMBO_STREAK_BONUSES: [
    { threshold: 10, points: 100 },
    { threshold: 25, points: 300 },
    { threshold: 50, points: 750 },
  ],

  // Particles
  PARTICLE_MAX: 400,
  PARTICLE_EXPLOSION_COUNT: 10,
  PARTICLE_SPARK_COUNT: 5,

  // Screen shake
  SHAKE_INTENSITY: 4,
  SHAKE_DURATION: 150,

  // Colors
  COLORS: {
    BG: '#0a0a1a',
    GRID: '#12122a',
    PLAYER: '#00e5ff',
    PLAYER_ACCENT: '#0077cc',
    PLAYER_SHIELD: 'rgba(0, 229, 255, 0.2)',
    BULLET: '#ffe033',
    BULLET_GLOW: '#ffaa00',
    SHARD_PRIMARY: '#e040fb',
    SHARD_SECONDARY: '#7c4dff',
    SHARD_TERTIARY: '#ff4081',
    SHARD_ARMORED: '#ff6e40',
    OBSTACLE: '#00e676',
    OBSTACLE_ACCENT: '#00895a',
    HAZARD_ORB: '#ff9100',
    HAZARD_RICOCHET: '#ff1744',
    HAZARD_DIVER: '#ffea00',
    HAZARD_CORRUPTION: '#aa00ff',
    UI_TEXT: '#ffffff',
    UI_SCORE: '#ffe033',
    UI_LIVES: '#00e5ff',
    UI_DANGER: '#ff1744',
    UI_TITLE_PRIMARY: '#e040fb',
    UI_TITLE_SECONDARY: '#00e5ff',
  },

  // Difficulty scaling
  DIFFICULTY_SPEED_SCALE: 0.04,
  DIFFICULTY_MAX_SPEED_MULT: 2.5,

  // Touch
  TOUCH_DEAD_ZONE: 5,
};
